# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7c44d447f51604dbf21792c1ef34abc914a90b7dee41ef0c629a3c73a84bfa11a50768bf504fee4c2722a42e1726abb646e37c0d68bd7077a642d75642723fd5

test:
  secret_key_base: ad71a701e9dcb7fedd8dc84a57c44186f420d79bdc8e56bc5ad48c23840d22271db18918f1c5834b559d6e547967219385d62c64a1c4b9412214534a9c5b4a1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
